Name=zero-lliurex-flash
Name[es]=Instalador de Adobe Flash Plugin
Name[qcv]=Instal·lador de l'Adobe Flash Plugin
Name[ca_ES]=Instal·lador de l'Adobe Flash Plugin
Comment=Adobe Flash Plugin
Comment[es]=Instalador de Adobe Flash Plugin
Comment[qcv]=Instal·lador de l'Adobe Flash Plugin
Comment[ca_ES]=Instal·lador de l'Adobe Flash Plugin
Icon=lliurex-flash-installer
Category=Software
ScriptPath=zero-lliurex-flash.zmd
Using=pkexec
Service=True
Groups=sudo;admins
