#!/bin/bash


ACTION="$1"

DEST_DOWNLOAD="/opt/photoglimmer/"
DEST_FILE="photoglimmer-appimage"
APPIMAGE="PhotoGlimmer_latest.AppImage"
URL="http://lliurex.net/recursos/"
DESKTOP_ORIG="/usr/share/zero-lliurex-photoglimmer/desktop/photoglimmer-appimage.desktop"
DESKTOP_DEST="/usr/share/applications/"


case $ACTION in

	getStatus)
		if [ -s ${DEST_DOWNLOAD}"/"${DEST_FILE} ]
		then	
			echo 0
		else
			echo 1	
		fi				
	;;

	download)

		if ! [ -d ${DEST_DOWNLOAD} ]
		then
			mkdir ${DEST_DOWNLOAD}
		fi

		cd ${DEST_DOWNLOAD}

		if [ -s ${DEST_DOWNLOAD}"/"${DEST_FILE} ]
		then
			rm -f ${DEST_DOWNLOAD}"/"${DEST_FILE}
		fi

		wget ${URL}${APPIMAGE} -O ${DEST_DOWNLOAD}${DEST_FILE}
		
		if ! [ -s ${DEST_DOWNLOAD}${DEST_FILE} ]
		then	
			exit 1
		fi	
	;;	
	
	installPackage)

		echo "Preparing PhotoGlimmer Appimage..."
		chown -R 755 ${DEST_DOWNLOAD}
		chmod +x ${DEST_DOWNLOAD}${DEST_FILE}
		
		cp $DESKTOP_ORIG $DESKTOP_DEST
		
		sleep 15

		update-desktop-database $DESKTOP_DEST >/dev/null 2>/dev/null || true
		
	;;

	remove)
		
		echo "Removing files..."

			
		if [ -s ${DEST_DOWNLOAD}${DEST_FILE} ]
		then
			rm -rf ${DEST_DOWNLOAD}
		fi

		if [ -s ${DEST_DOWNLOAD}${DEST_FILE} ]
		then	
			exit 1
		else
			rm -f ${DESKTOP_DEST}"/photoglimmer-appimage.desktop"
		fi	
	;;		
		
esac
exit 0