#!/bin/bash

ACTION="$1"

ANACONDA_URL_REPO=https://repo.anaconda.com/archive/
DESKTOP_ORIG="/usr/share/zero-lliurex-anaconda/anaconda-navigator.desktop"
DESKTOP_DEST="/usr/share/applications/"
DEST_DOWNLOAD=/var/cache/epi-downloads
DEST_FILE=anaconda.sh
ANACONDA_DIR=/opt/anaconda3
DEPENDS="libgl1-mesa-glx libegl1-mesa libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6"
export TEXTDOMAIN="zero-lliurex-anaconda"

QUESTION_MSG=$(gettext "Anaconda is already installed. To reinstall it's necessary to uninstall it previously.\nDo you want to continue?")


case $ACTION in

	getStatus)

		if [ -d ${ANACONDA_DIR} ];then
			echo 0
		else
			echo 1
		fi
	;;

	download)

		if ! [ -d  ${ANACONDA_DIR} ];then

			echo "Checking for last version..."
			ANACONDA_LAST_VERSION=$(wget --quiet -O - $ANACONDA_URL_REPO  | sed -e 's/<[^>]*>//g;/^\s*$/d' | grep Linux-x86_64.sh -m1)

			URL=$(echo ${ANACONDA_URL_REPO}${ANACONDA_LAST_VERSION} | tr -d ' ')

			wget ${URL} -O ${DEST_DOWNLOAD}/${DEST_FILE}

			if ! [ -f ${DEST_DOWNLOAD}"/"${DEST_FILE} ];then
				exit 1
			fi	
		fi
	;;

	preInstall)
		
		if ! [ -d ${ANACONDA_DIR} ];then
			apt-get install -y $DEPENDS
		fi
	;;

	installPackage)

		if ! [ -d ${ANACONDA_DIR} ];then
			cd ${DEST_DOWNLOAD}
			chmod +x ${DEST_FILE}

			./${DEST_FILE} -b -p ${ANACONDA_DIR}

			if ! [ -f ${ANACONDA_DIR}"/bin/anaconda-navigator" ]; then
				exit 1
			else
				cp  ${DESKTOP_ORIG} ${DESKTOP_DEST}
				cd ${ANACONDA_DIR}"/bin"
				./conda config --set auto_activate_base false

			fi
		else
			echo "Anaconda already installed. Nothing to do"
		fi
		
	;;

	remove)

		echo "Removing Anaconda installation..."

		if [ -d ${ANACONDA_DIR} ];then
			rm -rf ${ANACONDA_DIR}
		fi

		if [ -f ${DESKTOP_DEST}"/anaconda-navigator.desktop" ];then
			rm -f ${DESKTOP_DEST}"/anaconda-navigator.desktop"
		fi
	;;

esac
exit 0	