#!/bin/bash

ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	remove)
		count=0
		for ix in $PACKAGE_LIST
		do
			if [[ "$ix" == "io.github.antimicrox.antimicrox" ]];then
				flatpak uninstall $ix -y

				TEST=$(flatpak list | grep $ix | cut -d " " -f 1)

				if [[ ! -z "$TEST" ]];then
					count+=1
				fi
			fi
		done

		if [ $count -gt 0 ];then
			exit 1
		fi
	;;

esac
exit 0	
