Name=zero-lliurex-moodle
Name[en]=Instalación del Moodle
Name[es]=Instalación del Moodle
Name[qcv]=Instal·lació del Moodle
Name[ca_ES]=Instal·lació del Moodle
Comment=LliureX's Moodle
Comment[es]=Instalación del Moodle en LliureX
Comment[qcv]=Instal·lació del Moodle a LliureX
Comment[ca_ES]=Instal·lació del Moodle a LliureX
Icon=zero-lliurex-moodle
Groups=admin;admins;teachers;adm
Category=Services
ScriptPath=zero-lliurex-moodle.zmd
Using=pe 
Service=True
Depends=zero-server-wizard
