#!/bin/bash



ACTION="$1"
OLD_DESKTOP_PATH="/usr/share/mate/applications/spotify.desktop"

case $ACTION in

	postInstall)
		#Elimino el desktop para utilizar el proporcionado por lliurex-desktops-keeper
		echo "Removing Spotify desktop file..."
		if [ -f $OLD_DESKTOP_PATH ]; then
			rm -f $OLD_DESKTOP_PATH
		fi	
	;;	

	remove)
		apt-get remove -y spotify-client
		TEST=$( dpkg-query -s spotify-client 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi	
	;;	
esac
exit 0

