#!/bin/bash


ACTION="$1"
URL="https://deac-ams.dl.sourceforge.net/project/ai2offline/7.6/AI2Offline7.6.7z"
#This is a magic link, so it could change
URL_DATA="https://files.appinventor.mit.edu/api/public/dl/vlwV6uq3"
DEST_DOWNLOAD="/opt/ai2offline/"
DEST_FILE=$DEST_DOWNLOAD"ai2offline.7z"
AI2FOLDER=$DEST_DOWNLOAD"AI2Offline7.6/"
AISERVER_SCRIPT=$AI2FOLDER"startAIServer.sh"
AIBUILDER_SCRIPT=$AI2FOLDER"startBuildServer.sh"
DESKTOP_ORIG="/usr/share/zero-lliurex-ai2offline/desktops/*.desktop"
DESKTOP_DEST="/usr/share/applications/"
BIN_ORIG="/usr/share/zero-lliurex-ai2offline/bin/*"
BIN_DEST="/usr/bin/"
DEPENDS_AI2="lib32stdc++6 lib32z1"

case $ACTION in

	getStatus)
		if [ -s ${DEST_FILE} ]
		then	
			echo 0
		else
			echo 1	
		fi				
	;;

	download)

		if ! [ -d ${DEST_DOWNLOAD} ]
		then
			mkdir ${DEST_DOWNLOAD}
		fi

		cd ${DEST_DOWNLOAD}

		if [ -s ${DEST_FILE} ]
		then
			rm -f ${DEST_FILE}
			rm -rf ${AI2FOLDER}
		fi

		wget ${URL} -O ${DEST_FILE}
		wget ${URL_DATA} -O ${DEST_DATA}
		
		if ! [ -s ${DEST_FILE} ]
		then	
			exit 1
		fi	
	;;	

	preInstall)
		echo "Installing needed packages"
		for PKG in $DEPENDS_AI2
		do
			apt-get install --yes  $PKG
		done
	;;
	
	installPackage)

		echo "Unzip $DEST_FILE..."
		
		cd ${DEST_DOWNLOAD}
		7z x ${DEST_FILE}
		
		echo "Enable others write access..."
		chmod 777 -R ${AI2FOLDER}
		
		echo "Enable execution flag in scripts..."
		chmod +x ${AISERVER_SCRIPT}
		chmod +x ${AIBUILDER_SCRIPT}


		echo "Copy desktop files..."
		cp $DESKTOP_ORIG $DESKTOP_DEST
		sleep 5
		
		echo "Copy bin files..."
		cp $BIN_ORIG $BIN_DEST
		
	
	;;

	remove)
		
		echo "Removing files..."

	
		
		if [ -s ${DEST_DOWNLOAD}${DEST_FILE} ]
		then
			rm -f ${DEST_DOWNLOAD}${DEST_FILE}
		fi

		if [ -s ${DEST_DOWNLOAD}${DEST_FILE} ]
		then	
			exit 1
		fi
	


	;;		
		
esac
exit 0
