#!/bin/bash


ACTION="$1"

DEST_DOWNLOAD="/opt/lumi/"
APPIMAGE="Lumi.AppImage"
URL="http://lliurex.net/recursos/"
DESKTOP_ORIG="/usr/share/zero-lliurex-lumi/lumi.desktop"
DESKTOP_DEST="/usr/share/applications/"
MIME_DEST="/usr/share/mime/"
LINK_PATH="/usr/bin/lumi"


case $ACTION in

	getStatus)
		if [ -s ${DEST_DOWNLOAD}${APPIMAGE} ]
		then	
			echo 0
		else
			echo 1	
		fi				
	;;

	download)

		if ! [ -d ${DEST_DOWNLOAD} ]
		then
			mkdir ${DEST_DOWNLOAD}
		fi

		cd ${DEST_DOWNLOAD}

		if [ -s ${DEST_DOWNLOAD}${APPIMAGE} ]
		then
			rm -f ${DEST_DOWNLOAD}${APPIMAGE}
		fi

		wget ${URL}${APPIMAGE} -O ${DEST_DOWNLOAD}${APPIMAGE}

		if ! [ -s ${DEST_DOWNLOAD}${APPIMAGE} ]
		then	
			exit 1
		fi	
	;;	
	
	installPackage)

		echo "Preparing Lumi Appimage..."
		chmod +x ${DEST_DOWNLOAD}${APPIMAGE}
		chmod 775 ${DEST_DOWNLOAD}${APPIMAGE}

		if ! [ -e ${LINK_PATH} ]
		then
			echo "Creating link..."
			ln -s ${DEST_DOWNLOAD}${APPIMAGE} ${LINK_PATH}
		fi	

		echo "Adding desktop file..."
		cp ${DESKTOP_ORIG} ${DESKTOP_DEST}
		sleep 15
		update-desktop-database $DESKTOP_DEST >/dev/null 2>/dev/null || true
		
	;;

	remove)
		
		echo "Removing files..."

	
		
		if [ -s ${DEST_DOWNLOAD}${APPIMAGE} ]
		then
			rm -f ${DEST_DOWNLOAD}${APPIMAGE}
		fi

		if ! [ -e ${LINK_PATH} ]
		then
			rm -f ${LINK_PATH}
		fi

		if [ -s ${DEST_DOWNLOAD}${APPIMAGE} ]
		then	
			exit 1
		fi
	


	;;		
		
esac
exit 0