#!/bin/bash


ACTION="$1"
source_file="/etc/apt/sources.list.d/canonical.list"

case $ACTION in

	postInstall)
		
		if [ -f $source_file ];then
			echo "Removing canonical sources list"
			rm -f $source_file
		fi	 

	;;
	remove)
		apt-get remove -y adobe-flashplugin
		TEST=$( dpkg-query -s adobe-flashplugin 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi	
		if [ -f $source_file ];then
			rm -f $source_file
		fi	
	;;	
esac	

