#!/bin/bash



ACTION="$1"

case $ACTION in

	remove)
		apt-get remove -y google-chrome-stable
		TEST=$( dpkg-query -s google-chrome-stable 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi	
	;;	
esac
exit 0

