#!/bin/bash


ACTION="$1"

PACKAGE_LIST="nextcloud-desktop"

DEPENDS_LIST="nextcloud-desktop-common nextcloud-desktop-doc nextcloud-desktop-l10n"

case $ACTION in


	remove)

		for ix in $PACKAGE_LIST	
		do

			apt-get remove -y $ix
			TEST=$( dpkg-query -s  $ix 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				exit 1
			fi
		done

		for jx in $DEPENDS_LIST
		do
			apt-get remove -y $jx

		done		
				
	;;	
esac
exit 0