#!/bin/bash

ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	getStatus)
		RC=0
		snap list aws-cli|| RC=1
		if [ "$RC" = 0 ]
		then	
			echo 0
		else
			echo 1	
		fi				
	;;

	download)

		true
	;;	
	
	installPackage)

		snap install aws-cli --classic

	;;


	remove)
		count=0
		for ix in $PACKAGE_LIST
		do
		if [[ "$ix" == "aws-cli" ]];then
				snap remove $ix

				TEST=$(snap list | grep $ix | cut -d " " -f 1)

				if [[ ! -z "$TEST" ]];then
					count+=1
				fi
			fi
		done

		if [ $count -gt 0 ];then
			exit 1
		fi
	;;

esac
exit 0	