#!/bin/bash


ACTION="$1"

PACKAGE_LIST="lliurex-openmeetings-data lliurex-openmeetings-remote"


case $ACTION in
	preInstall)
		echo "Building kurento docker"
		docker pull kurento/kurento-media-server:latest
		docker run -d --name kms --network host kurento/kurento-media-server:latest

	postInstall)
		
		echo "Launching Openmeetings configurator"
		"lliurex-openmeetings-setup-qt"

	;;
	remove)

		for ix in $PACKAGE_LIST	
		do

			apt-get remove -y $ix
			TEST=$( dpkg-query -s  $ix 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				echo "$ix still installed"
				exit 1
			fi
		done		
	;;	
esac	

exit 0		
