#!/bin/bash


ACTION="$1"
SKYPE_SOURCES_LIST="/etc/apt/sources.list.d/skype-stable.list"

case $ACTION in

	postInstall)

		if [ -f $SKYPE_SOURCES_LIST ];then
			echo "Removing Skype sources list..."
			rm -f $SKYPE_SOURCES_LIST
		fi
	;;	

	remove)

		apt-get remove -y skypeforlinux
		TEST=$( dpkg-query -s  skypeforlinux 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi
				
	;;	
esac
exit 0