#!/bin/bash


ACTION="$1"
shift

PACKAGE_LIST=$@

case $ACTION in
	remove)
		for ix in $PACKAGE_LIST	
		do
			snap remove $ix

			TEST=$(snap list | grep $ix | cut -d " " -f 1)
			if [[ ! -z "$TEST" ]];then
				exit 1
			fi

		done
	;;	
esac	

