Name=zero-lliurex-salt
Name[es]=Instalación del SALT
Name[en]=SALT installation
Name[qcv]=Instal·lació del SALT 
Name[ca_ES]=Instal·lació del SALT
Comment=Installation of SALT wizard
Comment[es]=Asistente de instalación del SALT
Comment[qcv]=Auxiliar d'instal·lació del SALT
Comment[ca_ES]=Auxiliar d'instal·lació del SALT
Icon=zero-lliurex-salt
Groups=*
Category=Software
ScriptPath=zero-lliurex-salt.zmd
Using=pkexec
Service=True
