Name=zero-lliurex-anything-llm
Name[es]=Instalador de AnythingLLM
Name[en]=AnythingLLM installer
Name[ca@valencia]=Instal·lador de AnythingLLM
Name[qcv]=Instal·lador de AnythingLLM
Name[ca_ES]=Instal·lador de AnythingLLM
Comment=Allows you to install AnythingLLM Desktop to get local LLMs, RAG, and Agents with little to zero configuration and full privacy
Comment[es]=Permite instalar AnythingLLM Desktop para obtener LLM, RAG y agentes locales con poca o ninguna configuración y total privacidad
Comment[ca@valencia]=Permet instal·lar AnythingLLM Desktop per a obtindre LLM, RAG i agents locals amb poca o cap configuració i total privacitat
Comment[qcv]=Permet instal·lar AnythingLLM Desktop per a obtindre LLM, RAG i agents locals amb poca o cap configuració i total privacitat
Comment[ca_ES]=Permet instal·lar AnythingLLM Desktop per a obtindre LLM, RAG i agents locals amb poca o cap configuració i total privacitat
Groups=admin;admins;sudo;teachers
Category=Software
Icon=zero-lliurex-anything-llm
ScriptPath=zero-lliurex-anything-llm.zmd
Using=pkexec
Service=True
Show=False

