#!/bin/bash


ACTION="$1"


case $ACTION in

	postInstall)

		cd /opt
		# just in case something failed. we need a fresh start
		rm -rf openvino-models
		rm -rf /usr/lib/openvino-models

		mkdir openvino-models
		mkdir openvino-models/musicgen

		# MUSIC GEN
		git clone https://huggingface.co/Intel/musicgen-static-openvino

		unzip musicgen-static-openvino/musicgen_small_enc_dec_tok_openvino_models.zip -d openvino-models/musicgen
		unzip musicgen-static-openvino/musicgen_small_mono_openvino_models.zip -d openvino-models/musicgen
		unzip musicgen-static-openvino/musicgen_small_stereo_openvino_models.zip -d openvino-models/musicgen
		rm -rf musicgen-static-openvino
		
		# WHISPER
		git clone https://huggingface.co/Intel/whisper.cpp-openvino-models

		unzip whisper.cpp-openvino-models/ggml-base-models.zip -d openvino-models
		rm -rf whisper.cpp-openvino-models/ggml-base-models.zip
		unzip whisper.cpp-openvino-models/ggml-small-models.zip -d openvino-models
		rm -rf whisper.cpp-openvino-models/ggml-small-models.zip
		unzip whisper.cpp-openvino-models/ggml-small.en-tdrz-models.zip -d openvino-models

		rm -rf whisper.cpp-openvino-models
		
		# DEMUCS
		git clone https://huggingface.co/Intel/demucs-openvino

		mv demucs-openvino/htdemucs_v4.bin openvino-models
		mv demucs-openvino/htdemucs_v4.xml openvino-models

		rm -rf demucs-openvino

		# DEEPFILTERNET
		git clone https://huggingface.co/Intel/deepfilternet-openvino

		unzip deepfilternet-openvino/deepfilternet2.zip -d openvino-models
		rm -rf deepfilternet-openvino/deepfilternet2.zip
		unzip deepfilternet-openvino/deepfilternet3.zip -d openvino-models
		
		rm -rf  deepfilternet-openvino

		# NOISE SUPPRESION
		cd openvino-models
		wget https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/noise-suppression-denseunet-ll-0001/FP16/noise-suppression-denseunet-ll-0001.xml
		wget https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/noise-suppression-denseunet-ll-0001/FP16/noise-suppression-denseunet-ll-0001.bin
		cd ..

		# AUDIO SUPER RESOLUTION
		git clone https://huggingface.co/Intel/versatile_audio_super_resolution_openvino

		unzip versatile_audio_super_resolution_openvino/versatile_audio_sr_base_openvino_models.zip -d openvino-models/audiosr
		rm -rf versatile_audio_super_resolution_openvino/versatile_audio_sr_base_openvino_models.zip
		unzip versatile_audio_super_resolution_openvino/versatile_audio_sr_ddpm_basic_openvino_models.zip -d openvino-models/audiosr
		rm -rf versatile_audio_super_resolution_openvino/versatile_audio_sr_ddpm_basic_openvino_models.zip
		unzip versatile_audio_super_resolution_openvino/versatile_audio_sr_ddpm_speech_openvino_models.zip -d openvino-models/audiosr

		rm -rf versatile_audio_super_resolution_openvino

		# MOVE FILES TO SYSTEM DIR
		mv openvino-models /usr/lib
	;;	

	remove)
	

		OLD_AUDACITY=$(LANG=C apt policy audacity | grep Cand | cut -d ":" -f 2 | xargs)
		if [ -z $OLD_AUDACITY ];then
			echo "Error: Failed to query stable audacity version."
			exit 1

		fi

		# This operation should bring back stable audacity and remove custom audacity-ai
		# as we need to preserve lliurex-meta

		apt install -y audacity-data=$OLD_AUDACITY audacity=$OLD_AUDACITY
		rm -rf /usr/lib/openvino-models

	;;	

esac
exit 0
