#!/bin/bash


ACTION="$1"
shift

PACKAGE_LIST=$@

case $ACTION in
	postInstall)
		#Patch seeking for relevant line. Don't using patch here 
		TMPFILE=$(mktemp)
		cd /usr/share/luanti/builtin
		awk '{print $0;if ($0 ~ /local serverlist_url/) print "\tserverlist_url=\"\""}' mainmenu/serverlistmgr.lua > $TMPFILE
		mv $TMPFILE mainmenu/serverlistmgr.lua
		chmod 644 mainmenu/serverlistmgr.lua
		echo "**** Luanti/Minetest configured ****"
	;;
	remove)
		for ix in $PACKAGE_LIST	
		do
			apt-get remove -y $ix
			TEST=$( dpkg-query -s  $ix 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				exit 1

			fi
		done
	;;	
esac	

