#!/bin/bash


ACTION="$1"

BIN_ORIG="/usr/share/zero-lliurex-gtts/bin/lliurex-gtts"
BIN_DEST="/usr/bin/lliurex-gtts"

DESKTOP_ORIG="/usr/share/zero-lliurex-gtts/desktops/*.desktop"
DESKTOP_DEST="/usr/share/applications/"

APT_PACKAGES="python3-pip"
PIP_PACKAGES="gTTS"

INSTALLED_DIRS="/usr/local/lib/python*/dist-packages/gtts /usr/local/lib/python*/dist-packages/gTTS* /usr/local/bin/gtts-cli"


case $ACTION in

	remove)
		
		apt-get remove -y gtts-gui
                TEST=$( dpkg-query -s gtts-gui 2> /dev/null| grep Status | cut -d " " -f 4 )
                if [ "$TEST" == 'installed' ];then
			exit 1
                fi

	;;		
		
esac
exit 0
