#!/bin/bash


ACTION="$1"

case $ACTION in
	remove)
		flatpak uninstall org.kde.krita -y 
		TEST=$(flatpak list | grep org.kde.krita | cut -d " " -f 1)
		if [[ ! -z "$TEST" ]];then
			exit 1
		fi	;;	
esac	

