#!/bin/bash

ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	remove)
		
		flatpak uninstall org.bunkus.mkvtoolnix-gui -y
	
		TEST=$(flatpak list | grep org.bunkus.mkvtoolnix-gui | cut -d " " -f 1)
		if [[ ! -z "$TEST" ]];then
			exit 1
		fi
	;;

esac
exit 0	
