#!/bin/bash


ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	remove)
		for ix in $PACKAGE_LIST	
		do
			apt-get -y remove $ix
			TEST=$( dpkg-query -s  teams 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == $ix ];then
				exit 1
			fi	
		done	
				
	;;	
esac
exit 0