#!/bin/bash

ACTION="$1"

shift
PACKAGE_LIST=$@

case $ACTION in

	remove)
		count=0
		for ix in $PACKAGE_LIST
		do
			flatpak uninstall $ix -y
			flatpak uninstall io.github.manisandro.gImageReader.tessdata -y
			flatpak uninstall io.github.manisandro.gImageReader.Locale -y

			TEST=$(flatpak list | grep $ix | cut -d " " -f 1)

			if [[ ! -z "$TEST" ]];then
					count+=1
			fi

		done

		if [ $count -gt 0 ];then
			exit 1
		fi
	;;

esac
exit 0	
