#!/bin/bash



ACTION="$1"

case $ACTION in

	remove)
		apt-get remove -y azure-cli
		TEST=$( dpkg-query -s azure-cli 2> /dev/null| grep Status | cut -d " " -f 4 )
		if [ "$TEST" == 'installed' ];then
			exit 1
		fi	
	;;	
esac
exit 0

