#!/bin/bash


ACTION="$1"

DESTDOWNLOAD=$HOME"/Applications/"
APPIMAGE="FreeCAD_0.18-16146-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage"
URL="https://lliurex.net/recursos-edu/misc/"
DESKTOP_ORIG="/usr/share/zero-lliurex-freecad/freecad-appimage.desktop"
DESKTOP_DEST=$HOME"/.local/share/applications"
LINK=$HOME"/.local/bin/freecad-appimage"

case $ACTION in

	getStatus)
		if [ -s ${DESTDOWNLOAD}"/"${APPIMAGE} ]
		then	
			echo 0
		else
			echo 1	
		fi				
	;;

	download)

		cd ${DESTDOWNLOAD}

		if [ -s ${DESTDOWNLOAD}"/"${APPIMAGE} ]
		then
			rm -f ${DESTDOWNLOAD}"/"${APPIMAGE}
		fi

		wget ${URL}${APPIMAGE}
		
		if ! [ -s ${DESTDOWNLOAD}"/"${APPIMAGE} ]
		then	
			exit 1
		fi	
	;;	
	
	installPackage)

		echo "Preparing FreeCAD Appimage..."
		chmod +x $HOME/Applications/${APPIMAGE}
		
		if ! [ -e $LINK ]
		then
			ln -s $HOME/Applications/${APPIMAGE} $LINK
		fi	
		
		cp $DESKTOP_ORIG $DESKTOP_DEST

		update-mime-database $HOME/.local/share/mime >/dev/null 2>/dev/null || true
		update-desktop-database $DESKTOP_DEST >/dev/null 2>/dev/null || true
		
		echo ${APPIMAGE}" is now available at appimage-manager"
	;;

	remove)
		
		echo "Removing files..."

		if [ -e ${LINK} ]
		then
			rm -f $LINK
		fi

		
		if [ -s ${DESTDOWNLOAD}"/"${APPIMAGE} ]
		then
			rm -f ${DESTDOWNLOAD}"/"${APPIMAGE}
		fi

		if [ -s ${DESTDOWNLOAD}"/"${APPIMAGE} ]
		then	
			exit 1
		fi
	


	;;		
		
esac
exit 0